### ISSUE TITLE
Footer Creation

### ISSUE THREAD

**Issue by Deepak-Kumar201** [CodeFlowOrg/OpenForce-2022#48]
Footer for the site to be created as per the design shown below

![footer](https://user-images.githubusercontent.com/84946796/148281008-6f4332f1-eaad-45ed-8672-365e0256ed5f.png)

**Comment by rushikeshadhav** [comment]
Ok, working on footer

**Comment by rushikeshadhav** [comment]
Hey @cor1234 wait till you get assigned any issues.
Don't start working on them directly ask someone to assign you or you can comment.
