### ISSUE TITLE
About us design to be changed

### ISSUE THREAD

**Issue by Deepak-Kumar201** [CodeFlowOrg/OpenForce-2022#51]
Currently About us design is 

![Screenshot 2022-01-06 133755](https://user-images.githubusercontent.com/84946796/148350272-ebb8fbd5-cc19-4802-96bc-4e284e19f33a.png)

It is to be replaced with 

![Screenshot 2022-01-06 133431](https://user-images.githubusercontent.com/84946796/148350307-4e01dec7-0e63-4fc8-a1f0-d911a041e378.png)

**Comment by rushikeshadhav** [comment]
I am working on this

**Comment by Deepak-Kumar201** [comment]
Some one is already working on this vro
