### ISSUE TITLE
Correct the spelling of CodeFlow

### ISSUE THREAD

**Issue by chhabraharsh37** [CodeFlowOrg/OpenForce-2022#58]
![image](https://user-images.githubusercontent.com/60788180/148429302-81717425-f142-48f6-aa84-e4171d7c34c3.png)

Change the spelling of CodeFlow to Codeflow.

**Comment by tacosontitan** [comment]
Is the task to just remove the trailing whitespace?

**Comment by chhabraharsh37** [comment]
Yes, along with changing the name from "CodeFlow" to "Codeflow".
