### ISSUE TITLE
Icons adjustment

### ISSUE THREAD

**Issue by chhabraharsh37** [CodeFlowOrg/OpenForce-2022#64]
Also, add the icon of Codeflow YouTube and Discord.

YouTube link: https://www.youtube.com/c/Codefloworg
Discord link: https://discord.gg/XYWMBqCXPJ

![image](https://user-images.githubusercontent.com/60788180/148677351-c910fe74-3cf7-4d1b-baed-ee625de05ecc.png)

And the sequence of icons are as follow:
1) YouTube
2) Discord
3) LinkedIn
4) GitHub
5) Instagram
6) Twitter

**Comment by ishaanbedi** [comment]
Hi! I'd like to contribute to this! Can you assign it to me?
