### ISSUE TITLE
Local Environment setup instructions in Readme

### ISSUE THREAD

**Issue by iamparasbansal** [CodeFlowOrg/OpenForce-2022#84]
Local development environment setup instructions should be added in the readme. Preferably step-by-step!

**Comment by rushikeshadhav** [comment]
I think we should close this issue as the readme is updated and Local development environment setup instructions are added.

**Comment by rushikeshadhav** [comment]
Hey @Deepak-Kumar201 what else do you want to be added into the readme.
Let me know or we can close this issue
